#!/bin/bash

NODES=(54.72.221.170 54.72.227.166 54.72.221.206)

START=0
END=${#NODES[@]}-1

for ((NODE=START; NODE<=END; NODE++))
do
	echo "Configuring ${NODES[$NODE]} for user $1"
	./configure-node ~/.ssh/aws-key.pem ${NODES[$NODE]} $1
	echo "${NODES[$NODE]} configured"
done