#!/bin/bash

INSTALL_USER="ubuntu"
HADOOP_INSTALL="/var/hadoop"

#Update the repositories
apt-get update -y

#Download and install Java 6, git
apt-get install -y openjdk-6-jdk git

#Check if the JAVA_HOME is set and set it if not
if grep -q "^export JAVA_HOME" /home/$INSTALL_USER/.bashrc; then
	echo "JAVA_HOME already set"
else
	echo "JAVA_HOME not set"
	echo "export JAVA_HOME=/usr/lib/jvm/java-6-openjdk-amd64" >> ~/.bashrc
fi

#Check if the HADOOP_INSTALL is set and set it if not
if grep -q "^export HADOOP_INSTALL" /home/$INSTALL_USER/.bashrc; then
	echo "HADOOP_INSTALL already set"
else
	echo "HADOOP_INSTALL not set"
	echo "export HADOOP_INSTALL=$HADOOP_INSTALL" >> /home/$INSTALL_USER/.bashrc
fi

#Check if the HADOOP_CONF_DIR is set and set it if not
if grep -q "^export HADOOP_CONF_DIR" /home/$INSTALL_USER/.bashrc; then
	echo "HADOOP_CONF_DIR already set"
else
	echo "HADOOP_CONF_DIR not set"
	echo "export HADOOP_CONF_DIR=$HADOOP_INSTALL/conf" >> /home/$INSTALL_USER/.bashrc
fi

#Check if the HIVE_HOME is set and set it if not
if grep -q "^export HIVE_HOME" /home/$INSTALL_USER/.bashrc; then
	echo "HIVE_HOME already set"
else
	echo "HIVE_HOME not set"
	echo "export HIVE_HOME=$HADOOP_INSTALL/hive" >> /home/$INSTALL_USER/.bashrc
fi

#Check if the PIG_HOME is set and set it if not
if grep -q "^export PIG_HOME" /home/$INSTALL_USER/.bashrc; then
	echo "PIG_HOME already set"
else
	echo "PIG_HOME not set"
	echo "export PIG_HOME=$HADOOP_INSTALL/pig" >> /home/$INSTALL_USER/.bashrc
fi

#Check if the PIG_CLASSPATH is set and set it if not
if grep -q "^export PIG_CLASSPATH" /home/$INSTALL_USER/.bashrc; then
	echo "PIG_CLASSPATH already set"
else
	echo "PIG_CLASSPATH not set"
	echo "export PIG_CLASSPATH=${HADOOP_CONF_DIR}" >> /home/$INSTALL_USER/.bashrc
fi

#Check that the conf file points to the conf.aws folder
echo "Configuring HADOOP_CONF_DIR to use conf.aws file"
echo "export HADOOP_CONF_DIR=/$HADOOP_INSTALL/conf.aws" >> $HADOOP_INSTALL/conf/hadoop-env.sh

#Clone hadoop repository
if ! -e $HADOOP_INSTALL; then
	git clone https://github.com/sayden/hadoop-1.2.1.git $HADOOP_INSTALL
fi

# Set permissions
chown -R $INSTALL_USER $HADOOP_INSTALL
chgrp -R $INSTALL_USER $HADOOP_INSTALL

#Create the hdfs folder
if ! -e /var/hadoop/hdfs; then
	mkdir /var/hadoop/hdfs