#!/bin/bash

if [ $# -eq 2 ]; then
	echo "Sending file $1 to host $2"
	scp -i ~/.ssh/aws-key.pem $1 ubuntu@$2:/var/hadoop
elif [[ $# -eq 3 ]]; then
	echo "Sending file $1 to host $2 route $3"
	scp -i ~/.ssh/aws-key.pem $1 ubuntu@$2:$3
else
	echo 'Not enough arguments'
	echo "Use: send-to-master FILE MASTER-IP [ROUTE]"
	echo "If no route specified, it will send it to /home/ubuntu"
fi