#!/bin/bash

ssh slave1 'cd /var/hadoop/; git pull &'
ssh slave2 'cd /var/hadoop/; git pull &'
ssh slave3 'cd /var/hadoop/; git pull &'
ssh slave4 'cd /var/hadoop/; git pull &'
ssh slave5 'cd /var/hadoop/; git pull &'
ssh slave6 'cd /var/hadoop/; git pull &'
ssh slave7 'cd /var/hadoop/; git pull &'
ssh slave8 'cd /var/hadoop/; git pull &'
ssh slave9 'cd /var/hadoop/; git pull &'
ssh slave10 'cd /var/hadoop/; git pull &'